server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/USERDB"
    username: root
    password: root
    driver-class-name=com: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}${your-client-secret}"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080"
              post-logout-redirect-uris:
                - "http://localhost:8080/out"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true